<?php
require_once __DIR__.'/../includes/authorization.php';require_role('admin');require_once __DIR__.'/../includes/Repositories/ProductRepository.php';require_once __DIR__.'/../includes/Repositories/CategoryRepository.php';require_once __DIR__.'/../includes/Repositories/UserRepository.php';require_once __DIR__.'/../includes/validation.php';
$repo=new ProductRepository();$categories=(new CategoryRepository())->active();$sellers=(new UserRepository())->activeSellers();$errors=[];
$data=['seller_id'=>'','name'=>'','category'=>'','description'=>'','price'=>'','condition_label'=>'layak pakai','city'=>'','stock'=>'0','status'=>'available'];
if(is_post()){
 if(!verify_csrf())$errors[]='Sesi formulir tidak valid.';
 $data=['seller_id'=>filter_input(INPUT_POST,'seller_id',FILTER_VALIDATE_INT),'name'=>trim($_POST['name']??''),'category'=>trim($_POST['category']??''),'description'=>trim($_POST['description']??''),'price'=>trim($_POST['price']??''),'condition_label'=>trim($_POST['condition_label']??''),'city'=>trim($_POST['city']??''),'stock'=>trim($_POST['stock']??''),'status'=>$_POST['status']??'available'];
 $errors=array_merge($errors,validate_product_input($data));
 if(!$data['seller_id']||!array_filter($sellers,fn($s)=>(int)$s['id']===(int)$data['seller_id']))$errors[]='Seller aktif tidak valid.';
 if(!in_array($data['category'],array_column($categories,'name'),true))$errors[]='Kategori harus aktif.';
 if(!$errors){try{$id=$repo->create($data);$stock=(int)$data['stock'];$repo->setStockAdmin($id,$stock);if(!empty($_FILES['image']['name']))save_admin_product_image($id);flash('success','Produk berhasil dibuat oleh admin.');redirect(page_url('admin-products'));}catch(Throwable $e){$errors[]='Produk gagal dibuat. Periksa database dan data yang diinput.';}}
}
function save_admin_product_image(int $productId):void{
 if(($_FILES['image']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Upload gambar gagal.');
 if((int)$_FILES['image']['size']>5*1024*1024)throw new RuntimeException('Ukuran gambar maksimal 5 MB.');
 $tmp=$_FILES['image']['tmp_name'];$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($tmp);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
 if(!isset($allowed[$mime])||!@getimagesize($tmp))throw new RuntimeException('File harus JPG, PNG, atau WEBP.');
 $dir=__DIR__.'/../uploads/products';if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Folder upload tidak tersedia.');$name=bin2hex(random_bytes(16)).'.'.$allowed[$mime];if(!move_uploaded_file($tmp,$dir.'/'.$name))throw new RuntimeException('Gambar gagal disimpan.');db()->prepare('INSERT INTO product_images(product_id,image_path,sort_order) VALUES(?,?,0)')->execute([$productId,'uploads/products/'.$name]);
}
$pageTitle='Tambah Produk Admin';require __DIR__.'/../includes/header.php';
?>
<section class="auth-section"><div class="auth-shell"><div class="auth-intro"><div class="page-toolbar"><?=back_link('admin-products','Kembali ke produk admin')?></div><span class="eyebrow">Admin · Produk</span><h1>Tambah <em>produk.</em></h1><p>Admin dapat membuat produk untuk seller aktif. Produk tetap tercatat atas seller yang dipilih.</p></div><div class="auth-panel glass-card"><?php if($errors):?><div class="alert alert-danger small"><?=implode('<br>',array_map('e',$errors))?></div><?php endif;?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><label class="form-label">Seller</label><select class="form-select mb-3" name="seller_id" required><option value="">Pilih seller</option><?php foreach($sellers as $s):?><option value="<?=intval($s['id'])?>" <?=$data['seller_id']==$s['id']?'selected':''?>><?=e($s['full_name'])?> (@<?=e($s['username'])?>)</option><?php endforeach;?></select><label class="form-label">Nama produk</label><input class="form-control mb-3" name="name" value="<?=e((string)$data['name'])?>" required><label class="form-label">Kategori</label><select class="form-select mb-3" name="category" required><option value="">Pilih kategori</option><?php foreach($categories as $c):?><option value="<?=e($c['name'])?>" <?=$data['category']===$c['name']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select><label class="form-label">Deskripsi</label><textarea class="form-control mb-3" rows="5" name="description"><?=e((string)$data['description'])?></textarea><div class="row g-3"><div class="col-6"><label class="form-label">Harga</label><input class="form-control" type="number" min="0" name="price" value="<?=e((string)$data['price'])?>" required></div><div class="col-6"><label class="form-label">Stok</label><input class="form-control" type="number" min="0" name="stock" value="<?=e((string)$data['stock'])?>" required></div><div class="col-6"><label class="form-label">Kondisi</label><input class="form-control" name="condition_label" value="<?=e((string)$data['condition_label'])?>" required></div><div class="col-6"><label class="form-label">Kota</label><input class="form-control" name="city" value="<?=e((string)$data['city'])?>" required></div><div class="col-12"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach(['available','reserved','sold','archived'] as $s):?><option value="<?=$s?>" <?=$data['status']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></div><div class="col-12"><label class="form-label">Gambar utama</label><input class="form-control" type="file" name="image" accept="image/jpeg,image/png,image/webp"><small class="text-muted">JPG/PNG/WEBP, maksimal 5 MB.</small></div></div><button class="btn btn-primary w-100 mt-4">Buat produk <i class="bi bi-check2 ms-2"></i></button></form></div></div></section><?php require __DIR__.'/../includes/footer.php'; ?>
