<?php
require_once __DIR__.'/../includes/authorization.php';require_role('admin');require_once __DIR__.'/../includes/Repositories/UserRepository.php';
$repo=new UserRepository();$errors=[];$data=['full_name'=>'','username'=>'','shop_name'=>'','shop_city'=>'','shop_description'=>'','whatsapp'=>'','email'=>'','role'=>'seller','status'=>'active'];
if(is_post()){
 if(!verify_csrf())$errors[]='Sesi formulir tidak valid.';
 $data=['full_name'=>trim($_POST['full_name']??''),'username'=>trim($_POST['username']??''),'shop_name'=>trim($_POST['shop_name']??''),'shop_city'=>trim($_POST['shop_city']??''),'shop_description'=>trim($_POST['shop_description']??''),'whatsapp'=>normalize_phone(trim($_POST['whatsapp']??'')),'email'=>trim($_POST['email']??''),'role'=>$_POST['role']??'','status'=>$_POST['status']??'active'];$password=$_POST['password']??'';
 if(mb_strlen($data['full_name'])<3||mb_strlen($data['full_name'])>120)$errors[]='Nama lengkap 3-120 karakter.';
 if(!preg_match('/^[a-zA-Z0-9_]{4,30}$/',$data['username']))$errors[]='Username 4-30 karakter.';
 if(!filter_var($data['email'],FILTER_VALIDATE_EMAIL))$errors[]='Email tidak valid.';
 if(!preg_match('/^62[0-9]{9,15}$/',$data['whatsapp']))$errors[]='WhatsApp tidak valid.';
 if(!in_array($data['role'],['customer','seller','admin'],true))$errors[]='Role tidak valid.';
 if(!in_array($data['status'],['active','inactive','suspended'],true))$errors[]='Status tidak valid.';
 if(strlen($password)<8||!preg_match('/[A-Z]/',$password)||!preg_match('/[0-9]/',$password))$errors[]='Password minimal 8 karakter, huruf besar dan angka.';
 if(!$errors&&$repo->existsIdentity($data['username'],$data['email']))$errors[]='Username atau email sudah digunakan.';
 if(!$errors){$data['password']=$password;try{$repo->createByAdmin($data);flash('success','Pengguna berhasil dibuat.');redirect(page_url('admin-users'));}catch(Throwable $e){$errors[]='Pengguna gagal dibuat.';}}
}
$pageTitle='Tambah Pengguna';require __DIR__.'/../includes/header.php';
?>
<section class="auth-section"><div class="auth-shell"><div class="auth-intro"><div class="page-toolbar"><?=back_link('admin-users','Kembali ke pengguna')?></div><span class="eyebrow">Admin · Pengguna</span><h1>Tambah <em>pengguna.</em></h1><p>Gunakan halaman ini untuk membuat customer, seller, atau admin. Seller dibuat melalui admin, bukan register publik.</p></div><div class="auth-panel glass-card"><?php if($errors):?><div class="alert alert-danger small"><?=implode('<br>',array_map('e',$errors))?></div><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="row g-3"><div class="col-12"><label class="form-label">Nama lengkap</label><input class="form-control" name="full_name" value="<?=e($data['full_name'])?>" required></div><div class="col-md-6"><label class="form-label">Username</label><input class="form-control" name="username" value="<?=e($data['username'])?>" required></div><div class="col-md-6"><label class="form-label">WhatsApp</label><input class="form-control" name="whatsapp" value="<?=e($data['whatsapp'])?>" placeholder="08xxxxxxxxxx" required></div><div class="col-12"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?=e($data['email'])?>" required></div><div class="col-md-6"><label class="form-label">Role</label><select class="form-select" name="role"><option value="customer" <?=$data['role']==='customer'?'selected':''?>>customer</option><option value="seller" <?=$data['role']==='seller'?'selected':''?>>seller</option><option value="admin" <?=$data['role']==='admin'?'selected':''?>>admin</option></select></div><div class="col-md-6"><label class="form-label">Status</label><select class="form-select" name="status"><option value="active" <?=$data['status']==='active'?'selected':''?>>active</option><option value="inactive" <?=$data['status']==='inactive'?'selected':''?>>inactive</option><option value="suspended" <?=$data['status']==='suspended'?'selected':''?>>suspended</option></select></div><div class="col-12"><label class="form-label">Password awal</label><input class="form-control" type="password" name="password" required></div></div><button class="btn btn-primary w-100 mt-4">Buat pengguna <i class="bi bi-check2 ms-2"></i></button></form></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
