<?php
require_once __DIR__.'/../includes/authorization.php';require_role('admin');require_once __DIR__.'/../includes/Repositories/UserRepository.php';
$repo=new UserRepository();$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);if(!$id) { http_response_code(400); exit('User tidak valid.'); }$user=$repo->findById((int)$id);if(!$user){http_response_code(404);exit('User tidak ditemukan.');}$me=(int)$_SESSION['user_id'];$errors=[];$data=$user;
if(is_post()){
 if(!verify_csrf())$errors[]='Sesi formulir tidak valid.';
 $data=['full_name'=>trim($_POST['full_name']??''),'username'=>trim($_POST['username']??''),'whatsapp'=>normalize_phone(trim($_POST['whatsapp']??'')),'email'=>trim($_POST['email']??''),'role'=>$_POST['role']??'','status'=>$_POST['status']??'','password'=>$_POST['password']??''];
 if(mb_strlen($data['full_name'])<3||mb_strlen($data['full_name'])>120)$errors[]='Nama lengkap 3-120 karakter.';
 if(!preg_match('/^[a-zA-Z0-9_]{4,30}$/',$data['username']))$errors[]='Username 4-30 karakter.';
 if(!filter_var($data['email'],FILTER_VALIDATE_EMAIL))$errors[]='Email tidak valid.';
 if(!preg_match('/^62[0-9]{9,15}$/',$data['whatsapp']))$errors[]='WhatsApp tidak valid.';
 if(!in_array($data['role'],['customer','seller','admin'],true)||!in_array($data['status'],['active','inactive','suspended'],true))$errors[]='Role/status tidak valid.';
 if($data['password']!==''&&(strlen($data['password'])<8||!preg_match('/[A-Z]/',$data['password'])||!preg_match('/[0-9]/',$data['password'])))$errors[]='Password baru minimal 8 karakter, huruf besar dan angka.';
 if((int)$id===$me&&($data['role']!=='admin'||$data['status']!=='active'))$errors[]='Admin aktif yang sedang login tidak boleh menurunkan role atau menonaktifkan dirinya sendiri.';
 if(!$errors&&$repo->existsIdentity($data['username'],$data['email'],(int)$id))$errors[]='Username atau email sudah digunakan.';
 if(!$errors){try{$repo->updateAdmin((int)$id,$data);flash('success','Data pengguna diperbarui.');redirect(page_url('admin-users'));}catch(Throwable $e){$errors[]='Data pengguna gagal diperbarui.';}}
}
$pageTitle='Edit Pengguna';require __DIR__.'/../includes/header.php';
?>
<section class="auth-section"><div class="auth-shell"><div class="auth-intro"><div class="page-toolbar"><?=back_link('admin-users','Kembali ke pengguna')?></div><span class="eyebrow">Admin · Pengguna</span><h1>Edit <em>pengguna.</em></h1><p>Ubah data, role, status, atau password user. Histori transaksi tetap dipertahankan.</p></div><div class="auth-panel glass-card"><?php if($errors):?><div class="alert alert-danger small"><?=implode('<br>',array_map('e',$errors))?></div><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="row g-3"><div class="col-12"><label class="form-label">Nama lengkap</label><input class="form-control" name="full_name" value="<?=e($data['full_name'])?>" required></div><div class="col-md-6"><label class="form-label">Username</label><input class="form-control" name="username" value="<?=e($data['username'])?>" required></div><div class="col-md-6"><label class="form-label">WhatsApp</label><input class="form-control" name="whatsapp" value="<?=e($data['whatsapp'])?>" required></div><div class="col-12"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?=e($data['email'])?>" required></div><div class="col-md-6"><label class="form-label">Role</label><select class="form-select" name="role"><option value="customer" <?=$data['role']==='customer'?'selected':''?>>customer</option><option value="seller" <?=$data['role']==='seller'?'selected':''?>>seller</option><option value="admin" <?=$data['role']==='admin'?'selected':''?>>admin</option></select></div><div class="col-md-6"><label class="form-label">Status</label><select class="form-select" name="status"><option value="active" <?=$data['status']==='active'?'selected':''?>>active</option><option value="inactive" <?=$data['status']==='inactive'?'selected':''?>>inactive</option><option value="suspended" <?=$data['status']==='suspended'?'selected':''?>>suspended</option></select></div><div class="col-12"><label class="form-label">Password baru <span class="text-muted fw-normal">(opsional)</span></label><input class="form-control" type="password" name="password" placeholder="Kosongkan jika tidak diubah"></div></div><button class="btn btn-primary w-100 mt-4">Simpan perubahan <i class="bi bi-check2 ms-2"></i></button></form></div></div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
