<?php
$pageTitle = 'Marketplace Reuseable untuk Anak Kos';
require __DIR__ . '/../includes/header.php';
$products = [
    ['name' => 'Kursi kerja minimalis', 'category' => 'Furnitur', 'price' => 175000, 'icon' => 'bi-lamp'],
    ['name' => 'Rak susun serbaguna', 'category' => 'Organisasi', 'price' => 90000, 'icon' => 'bi-grid-3x3-gap'],
    ['name' => 'Set alat masak', 'category' => 'Dapur', 'price' => 125000, 'icon' => 'bi-cup-hot'],
];
?>
<section class="hero-section">
    <div class="container position-relative">
        <div class="hero-orbit orbit-one"></div><div class="hero-orbit orbit-two"></div>
        <div class="row align-items-center g-5">
            <div class="col-lg-7 hero-copy reveal"><span class="eyebrow"><i class="bi bi-stars"></i> Marketplace anak kos</span><h1>Barang baik,<br><em>cerita baru.</em></h1><p class="hero-lead">Temukan barang bekas layak pakai di sekitar kamu. Lebih hemat, lebih dekat, dan lebih ramah bumi.</p><div class="d-flex flex-wrap gap-3"><a href="#katalog" class="btn btn-primary btn-lg">Jelajahi katalog <i class="bi bi-arrow-down-right ms-2"></i></a><a href="#cara-pesan" class="btn btn-ghost btn-lg">Cara kerja <i class="bi bi-play-circle ms-2"></i></a></div><div class="hero-proof mt-5"><div class="avatar-stack"><span>AR</span><span>DN</span><span>KS</span></div><div><strong>Dipilih oleh anak kos</strong><small>Hemat tanpa kompromi</small></div></div></div>
            <div class="col-lg-5 reveal delay-1"><div class="hero-card glass-card"><div class="card-topline"><span class="live-dot"></span> Sedang berputar</div><div class="hero-object"><div class="object-glow"></div><i class="bi bi-house-heart-fill"></i></div><div class="hero-card-info"><div><span class="text-muted small">Pilihan minggu ini</span><h3>Sudut nyaman baru</h3></div><span class="price-pill">mulai 50K</span></div><div class="mini-progress"><span></span></div><small class="text-muted">82 barang menemukan pemilik baru bulan ini</small></div></div>
        </div>
    </div>
</section>
<section class="stats-strip"><div class="container"><div class="row g-4"><div class="col-4 stat-item"><strong>1.2K+</strong><span>barang berputar</span></div><div class="col-4 stat-item"><strong>350+</strong><span>anak kos terhubung</span></div><div class="col-4 stat-item"><strong>24 kota</strong><span>dan terus bertambah</span></div></div></div></section>
<section class="section-padding" id="katalog"><div class="container"><div class="section-heading d-flex justify-content-between align-items-end mb-4"><div><span class="eyebrow">Temukan barangmu</span><h2>Yang sedang <em>dicari.</em></h2></div><a class="text-link" href="<?= APP_URL ?>/?page=login">Lihat semua <i class="bi bi-arrow-up-right"></i></a></div><div class="row g-4"><?php foreach ($products as $product): ?><div class="col-md-4"><article class="product-card glass-card"><div class="product-visual"><span class="product-tag"><?= e($product['category']) ?></span><i class="bi <?= e($product['icon']) ?>"></i><span class="product-condition">layak pakai</span></div><div class="p-3"><div class="d-flex justify-content-between align-items-start"><div><h3><?= e($product['name']) ?></h3><small class="text-muted"><i class="bi bi-geo-alt me-1"></i>Jakarta Selatan · 2 km</small></div><i class="bi bi-heart icon-muted"></i></div><div class="d-flex justify-content-between align-items-center mt-3"><strong class="product-price"><?= format_price($product['price']) ?></strong><a class="btn btn-sm btn-soft" href="<?= APP_URL ?>/?page=login" title="Login untuk memesan"><i class="bi bi-lock me-1"></i>Pesan</a></div></div></article></div><?php endforeach; ?></div></div></section>
<section class="section-padding process-section" id="cara-pesan"><div class="container"><div class="row g-5 align-items-start"><div class="col-lg-5"><span class="eyebrow"><i class="bi bi-arrow-repeat"></i> Alur KosCycle</span><h2>Pesan dengan<br><em>lebih tenang.</em></h2><p class="text-muted">Dari menemukan barang sampai bertemu pemiliknya, semua langkah dibuat sederhana dan transparan.</p><a href="<?= current_user() ? APP_URL . '/#katalog' : APP_URL . '/?page=login' ?>" class="btn btn-primary mt-3"><?= current_user() ? 'Cari barang sekarang' : 'Masuk untuk mulai' ?> <i class="bi bi-arrow-right ms-2"></i></a></div><div class="col-lg-7"><div class="process-list"><div class="process-step"><span class="process-number">01</span><div class="process-content"><h3>Jelajahi katalog</h3><p>Pilih barang berdasarkan kategori, kondisi, harga, dan lokasi terdekat.</p></div><span class="process-icon"><i class="bi bi-search"></i></span></div><div class="process-step"><span class="process-number">02</span><div class="process-content"><h3>Login atau daftar</h3><p>Masuk ke akun KosCycle sebelum memesan agar data transaksi tercatat aman.</p></div><span class="process-icon"><i class="bi bi-person-check"></i></span></div><div class="process-step"><span class="process-number">03</span><div class="process-content"><h3>Kirim permintaan pesan</h3><p>Klik tombol Pesan pada barang yang kamu inginkan dan hubungi seller.</p></div><span class="process-icon"><i class="bi bi-chat-heart"></i></span></div><div class="process-step"><span class="process-number">04</span><div class="process-content"><h3>Sepakati serah terima</h3><p>Atur waktu dan tempat bertemu yang aman, lalu selesaikan transaksi langsung.</p></div><span class="process-icon"><i class="bi bi-hand-thumbs-up"></i></span></div></div></div></div></div></section>
<?php require __DIR__ . '/../includes/footer.php'; ?>