<?php
require_once __DIR__.'/../includes/authorization.php';require_auth();require_once __DIR__.'/../includes/Repositories/UserRepository.php';
$repo=new UserRepository();$user=current_user();$errors=[];
if(is_post()){
 if(!verify_csrf())$errors[]='Sesi formulir tidak valid.';
 $data=['full_name'=>trim($_POST['full_name']??''),'username'=>trim($_POST['username']??''),'whatsapp'=>normalize_phone(trim($_POST['whatsapp']??'')),'email'=>trim($_POST['email']??'')];
 if(mb_strlen($data['full_name'])<3||mb_strlen($data['full_name'])>120)$errors[]='Nama lengkap 3-120 karakter.';
 if(!preg_match('/^[a-zA-Z0-9_]{4,30}$/',$data['username']))$errors[]='Username 4-30 karakter dan hanya huruf, angka, underscore.';
 if(!filter_var($data['email'],FILTER_VALIDATE_EMAIL))$errors[]='Email tidak valid.'; if(!preg_match('/^62[0-9]{9,15}$/',$data['whatsapp']))$errors[]='Nomor WhatsApp tidak valid.';
 if(!$errors){$st=db()->prepare('SELECT id FROM users WHERE (username=? OR email=?) AND id<>? LIMIT 1');$st->execute([$data['username'],$data['email'],(int)$user['id']]);if($st->fetch())$errors[]='Username atau email sudah digunakan.';}
 if(!$errors){$repo->updateProfile((int)$user['id'],$data);flash('success','Profil berhasil diperbarui.');redirect(page_url('profile'));}
}
$pageTitle='Profil';require __DIR__.'/../includes/header.php';
?><section class="section-padding page-section"><div class="container"><div class="page-toolbar"><?=back_link(dashboard_page_for_role($user['role']),'Kembali ke dashboard')?></div><div class="section-heading mb-4"><span class="eyebrow">Profil</span><h2>Data <em>akun.</em></h2><p class="text-muted">Kelola data yang digunakan dalam aktivitas KosCycle.</p></div><div class="glass-card p-4 p-lg-5"><?php if($errors):?><div class="alert alert-danger"><?=implode('<br>',array_map('e',$errors))?></div><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="row g-3"><div class="col-md-6"><label class="form-label">Nama lengkap</label><input class="form-control" name="full_name" value="<?=e($user['full_name'])?>"></div><div class="col-md-6"><label class="form-label">Username</label><input class="form-control" name="username" value="<?=e($user['username'])?>"></div><div class="col-md-6"><label class="form-label">WhatsApp</label><input class="form-control" name="whatsapp" value="<?=e($user['whatsapp'])?>"></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?=e($user['email'])?>"></div></div><button class="btn btn-primary mt-4">Simpan perubahan</button></form></div></div></section><?php require __DIR__.'/../includes/footer.php'; ?>