<?php
require_once __DIR__ . '/../includes/auth.php'; require_guest();
$errors = [];
if (is_post()) {
    $data = ['full_name'=>trim($_POST['full_name'] ?? ''), 'username'=>trim($_POST['username'] ?? ''), 'whatsapp'=>trim($_POST['whatsapp'] ?? ''), 'email'=>trim($_POST['email'] ?? ''), 'role'=>$_POST['role'] ?? 'customer'];
    $password = $_POST['password'] ?? ''; $confirmation = $_POST['password_confirmation'] ?? '';
    if (!verify_csrf()) $errors[] = 'Sesi formulir tidak valid.';
    if (mb_strlen($data['full_name']) < 3) $errors[] = 'Nama lengkap minimal 3 karakter.';
    if (!preg_match('/^[a-zA-Z0-9_]{4,30}$/', $data['username'])) $errors[] = 'Username 4-30 karakter, hanya huruf, angka, dan underscore.';
    if (!filter_var($data['email'], FILTER_VALIDATE_EMAIL)) $errors[] = 'Format email belum valid.';
    if (!in_array($data['role'], ['customer', 'seller'], true)) $errors[] = 'Tipe akun tidak valid.';
    if (!preg_match('/^(08|62)[0-9]{8,13}$/', preg_replace('/[^0-9]/', '', $data['whatsapp']))) $errors[] = 'Nomor WhatsApp belum valid.';
    if (strlen($password) < 8 || !preg_match('/[A-Z]/', $password) || !preg_match('/[0-9]/', $password)) $errors[] = 'Password minimal 8 karakter dan harus memiliki huruf besar serta angka.';
    if ($password !== $confirmation) $errors[] = 'Konfirmasi password tidak sama.';
    if (!$errors) { $check = db()->prepare('SELECT id FROM users WHERE username = ? OR email = ?'); $check->execute([$data['username'], $data['email']]); if ($check->fetch()) $errors[] = 'Username atau email sudah digunakan.'; }
    if (!$errors) { $stmt = db()->prepare('INSERT INTO users (full_name, username, whatsapp, email, password_hash, role) VALUES (?, ?, ?, ?, ?, ?)'); $stmt->execute([$data['full_name'], $data['username'], normalize_phone($data['whatsapp']), $data['email'], password_hash($password, PASSWORD_DEFAULT), $data['role']]); flash('success', 'Akun ' . ($data['role'] === 'seller' ? 'seller' : 'customer') . ' berhasil dibuat. Silakan masuk.'); redirect(APP_URL . '/?page=login'); }
    set_old($data);
}
$pageTitle = 'Daftar'; require __DIR__ . '/../includes/header.php';
?><section class="auth-section"><div class="auth-shell auth-shell-wide"><div class="auth-intro"><span class="eyebrow">Mulai berputar</span><h1>Satu akun,<br><em>banyak kemungkinan.</em></h1><p>Gabung ke komunitas anak kos yang memilih hemat, dekat, dan lebih berkelanjutan.</p><div class="benefit-list"><div><i class="bi bi-check2-circle"></i><span>Temukan barang di sekitar kamu</span></div><div><i class="bi bi-check2-circle"></i><span>Jual barang yang sudah tidak terpakai</span></div><div><i class="bi bi-check2-circle"></i><span>Transaksi dengan lebih nyaman</span></div></div></div><div class="auth-panel glass-card"><div class="auth-heading"><span class="auth-icon"><i class="bi bi-person-plus"></i></span><div><h2>Buat akun baru</h2><p>Gratis, cepat, dan aman.</p></div></div><?php if ($errors): ?><div class="alert alert-danger small"><?= implode('<br>', array_map('e', $errors)) ?></div><?php endif; ?><form method="post" novalidate><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="row g-3"><div class="col-12"><label class="form-label">Nama lengkap</label><input class="form-control" name="full_name" value="<?= old('full_name') ?>" placeholder="Nama kamu"></div><div class="col-md-6"><label class="form-label">Username</label><input class="form-control" name="username" value="<?= old('username') ?>" placeholder="contoh: anak_kos"></div><div class="col-md-6"><label class="form-label">Nomor WhatsApp</label><input class="form-control" name="whatsapp" value="<?= old('whatsapp') ?>" placeholder="08xxxxxxxxxx"></div><div class="col-12"><label class="form-label">Email aktif</label><input class="form-control" type="email" name="email" value="<?= old('email') ?>" placeholder="kamu@email.com"></div><div class="col-md-6"><label class="form-label">Password</label><input class="form-control" type="password" name="password" placeholder="Min. 8 karakter"></div><div class="col-md-6"><label class="form-label">Konfirmasi password</label><input class="form-control" type="password" name="password_confirmation" placeholder="Ulangi password"></div></div><div class="form-hint mt-3"><i class="bi bi-info-circle me-1"></i> Gunakan huruf besar dan angka dalam password.</div><button class="btn btn-primary w-100 mt-4" type="submit">Buat akun <i class="bi bi-arrow-right ms-2"></i></button></form><p class="auth-switch">Sudah punya akun? <a href="<?= APP_URL ?>/?page=login">Masuk di sini</a></p></div></div></section><?php require __DIR__ . '/../includes/footer.php'; ?>