<?php
require_once __DIR__.'/../includes/authorization.php';require_role('seller');require_once __DIR__.'/../includes/Repositories/ProductRepository.php';require_once __DIR__.'/../includes/Repositories/CategoryRepository.php';require_once __DIR__.'/../includes/validation.php';
$repo=new ProductRepository();$categories=(new CategoryRepository())->active();$sellerId=(int)$_SESSION['user_id'];$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$editing=(bool)$id;$existing=$editing?$repo->find((int)$id,false):null;
if($editing&&(!$existing||(int)$existing['seller_id']!==$sellerId)){http_response_code(404);exit('Produk tidak ditemukan.');}
$data=$existing?['name'=>$existing['name'],'category'=>$existing['category'],'description'=>$existing['description'],'price'=>$existing['price'],'condition_label'=>$existing['condition_label'],'city'=>$existing['city'],'stock'=>$existing['stock'],'status'=>$existing['status']]:['name'=>'','category'=>'','description'=>'','price'=>'','condition_label'=>'layak pakai','city'=>'','stock'=>0,'status'=>'available'];$errors=[];
if(is_post()){
 if(!verify_csrf())$errors[]='Sesi formulir tidak valid.';
 $data=['name'=>trim($_POST['name']??''),'category'=>trim($_POST['category']??''),'description'=>trim($_POST['description']??''),'price'=>trim($_POST['price']??''),'condition_label'=>trim($_POST['condition_label']??''),'city'=>trim($_POST['city']??''),'stock'=>trim($_POST['stock']??''),'status'=>$_POST['status']??'available'];
 $errors=array_merge($errors,validate_product_input($data));if(!in_array($data['status'],['available','reserved','sold','archived'],true))$errors[]='Status produk tidak valid.';
 $catNames=array_column($categories,'name');if(!$categories)$errors[]='Belum ada kategori aktif. Admin harus membuat kategori terlebih dahulu.';elseif(!in_array($data['category'],$catNames,true))$errors[]='Kategori tidak valid.';
 if(!$errors){try{if($editing){$repo->update((int)$id,$sellerId,$data);$repo->setStock((int)$id,$sellerId,(int)$data['stock']);handle_product_upload((int)$id,$sellerId);flash('success','Produk berhasil diperbarui.');}else{$newId=$repo->create(['seller_id'=>$sellerId]+$data);try{handle_product_upload($newId,$sellerId);}catch(Throwable $uploadError){$repo->archive($newId,$sellerId);throw $uploadError;}flash('success','Produk berhasil dibuat dan masuk ke katalog.');}redirect(page_url('seller-products'));}catch(Throwable $e){$errors[]='Produk gagal disimpan. Pastikan database.mysql sudah dijalankan dan folder uploads/products dapat ditulis.';}}
}
function handle_product_upload(int $productId,int $sellerId):void{
 if(empty($_FILES['image']['name']))return;$check=db()->prepare('SELECT id FROM products WHERE id=? AND seller_id=? LIMIT 1');$check->execute([$productId,$sellerId]);if(!$check->fetchColumn())throw new RuntimeException('Ownership produk tidak valid.');
 if(($_FILES['image']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Upload gambar gagal.');if((int)$_FILES['image']['size']>5*1024*1024)throw new RuntimeException('Ukuran gambar maksimal 5 MB.');$tmp=$_FILES['image']['tmp_name'];$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($tmp);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
 if(!isset($allowed[$mime])||!@getimagesize($tmp))throw new RuntimeException('File harus gambar JPG, PNG, atau WEBP.');$dir=__DIR__.'/../uploads/products';if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Folder upload tidak tersedia.');$name=bin2hex(random_bytes(16)).'.'.$allowed[$mime];$path=$dir.'/'.$name;if(!move_uploaded_file($tmp,$path))throw new RuntimeException('Gambar gagal disimpan.');db()->prepare('INSERT INTO product_images(product_id,image_path,sort_order) VALUES(?,?,0)')->execute([$productId,'uploads/products/'.$name]);
}
$pageTitle=$editing?'Edit Produk':'Tambah Produk';require __DIR__.'/../includes/header.php';
?><section class="auth-section"><div class="auth-shell"><div class="auth-intro"><div class="page-toolbar"><?=back_link('seller-products','Kembali ke produk saya')?></div><span class="eyebrow">Seller</span><h1><?=$editing?'Edit':'Tambah'?> <em>produk.</em></h1><p>Produk yang disimpan akan langsung menjadi bagian dari katalog seller dan dapat ditemukan customer sesuai status dan stok.</p></div><div class="auth-panel glass-card"><?php if($errors):?><div class="alert alert-danger"><?=implode('<br>',array_map('e',$errors))?></div><?php endif;?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><label class="form-label">Nama produk</label><input class="form-control mb-3" name="name" value="<?=e((string)$data['name'])?>" required><label class="form-label">Kategori</label><select class="form-select mb-3" name="category" required><option value="">Pilih kategori</option><?php foreach($categories as $c):?><option value="<?=e($c['name'])?>" <?=$data['category']===$c['name']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select><label class="form-label">Deskripsi</label><textarea class="form-control mb-3" rows="5" name="description"><?=e((string)$data['description'])?></textarea><div class="row g-3"><div class="col-6"><label class="form-label">Harga</label><input class="form-control" type="number" min="0" name="price" value="<?=e((string)$data['price'])?>" required></div><div class="col-6"><label class="form-label">Stok</label><input class="form-control" type="number" min="0" name="stock" value="<?=e((string)$data['stock'])?>" required></div><div class="col-6"><label class="form-label">Kondisi</label><input class="form-control" name="condition_label" value="<?=e((string)$data['condition_label'])?>" required></div><div class="col-6"><label class="form-label">Kota</label><input class="form-control" name="city" value="<?=e((string)$data['city'])?>" required></div><div class="col-12"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach(['available','reserved','sold','archived'] as $s):?><option value="<?=$s?>" <?=$data['status']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></div><div class="col-12"><label class="form-label">Gambar utama</label><input class="form-control" type="file" name="image" accept="image/jpeg,image/png,image/webp"><small class="text-muted">JPG/PNG/WEBP, maksimal 5 MB.</small></div></div><button class="btn btn-primary w-100 mt-4"><?=$editing?'Simpan perubahan':'Tambah ke katalog'?> <i class="bi bi-arrow-right ms-2"></i></button></form></div></div></section><?php require __DIR__.'/../includes/footer.php'; ?>