<?php
require_once __DIR__.'/../includes/authorization.php';require_role('seller');require_once __DIR__.'/../includes/Repositories/OrderRepository.php';
$repo=new OrderRepository();$sellerId=(int)$_SESSION['user_id'];$errors=[];$transitions=['requested'=>['accepted','cancelled'],'accepted'=>['completed','cancelled'],'completed'=>[],'cancelled'=>[]];
if(is_post()){
 if(!verify_csrf()){flash('error','Sesi formulir tidak valid.');redirect(page_url('seller-orders'));}$orderId=filter_input(INPUT_POST,'order_id',FILTER_VALIDATE_INT);$new=$_POST['status']??'';
 $items=$orderId?$repo->sellerOrderItems((int)$orderId,$sellerId):[];$stmt=$orderId?db()->prepare('SELECT status FROM orders WHERE id=? LIMIT 1'):null;if($stmt)$stmt->execute([$orderId]);$current=$stmt?$stmt->fetchColumn():false;
 if(!$orderId||!$items||!isset($transitions[$current])||!in_array($new,$transitions[$current],true))$errors[]='Perubahan status tidak valid atau pesanan bukan milik produkmu.';else{$repo->setStatusSeller((int)$orderId,$sellerId,$new);flash('success','Status pesanan diperbarui.');redirect(page_url('seller-orders'));}
}
$orders=$repo->sellerOrders($sellerId);$pageTitle='Pesanan Seller';require __DIR__.'/../includes/header.php';
?><section class="section-padding page-section"><div class="container"><div class="page-toolbar"><?=back_link('seller-dashboard','Kembali ke dashboard')?></div><div class="section-heading mb-4"><span class="eyebrow">Seller</span><h2>Kelola <em>pesanan.</em></h2><p class="text-muted">Lihat pesanan customer dan perbarui status sesuai alur.</p></div><?php if($errors):?><div class="alert alert-danger"><?=implode('<br>',array_map('e',$errors))?></div><?php endif;?><?php if(!$orders):?><div class="glass-card empty-state"><span><i class="bi bi-bag-check"></i></span><h2>Belum ada pesanan</h2><p>Pesanan dari customer akan muncul di sini.</p></div><?php endif;?><?php foreach($orders as $o):?><div class="glass-card p-4 mb-3"><div class="d-flex justify-content-between gap-3"><div><strong>Pesanan #<?=intval($o['id'])?></strong><div class="text-muted mt-1"><?=e($o['buyer_name'])?> · <?=e($o['buyer_whatsapp'])?></div></div><span class="badge text-bg-light align-self-start"><?=e($o['status'])?></span></div><div class="mt-2"><strong><?=format_price((int)$o['total'])?></strong> <span class="text-muted">· <?=e($o['created_at'])?></span></div><?php $items=$repo->sellerOrderItems((int)$o['id'],$sellerId);?><?php foreach($items as $it):?><div class="border-top mt-3 pt-3"><div class="d-flex justify-content-between"><span><?=e($it['product_name'])?> × <?=intval($it['quantity'])?></span><strong><?=format_price((int)$it['line_total'])?></strong></div></div><?php endforeach;?><?php if($transitions[$o['status']]??[]):?><form class="d-flex gap-2 mt-3" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="order_id" value="<?=intval($o['id'])?>"><select class="form-select" name="status"><?php foreach($transitions[$o['status']] as $s):?><option value="<?=$s?>"><?=$s?></option><?php endforeach;?></select><button class="btn btn-primary">Simpan status</button></form><?php endif;?></div><?php endforeach;?></div></section><?php require __DIR__.'/../includes/footer.php'; ?>