<?php
require_once __DIR__.'/../includes/authorization.php';require_role('seller');require_once __DIR__.'/../includes/Repositories/ProductRepository.php';
$repo=new ProductRepository();$sellerId=(int)$_SESSION['user_id'];
if(is_post()){
 if(!verify_csrf()){flash('error','Sesi formulir tidak valid.');redirect(page_url('seller-products'));}
 $id=filter_input(INPUT_POST,'product_id',FILTER_VALIDATE_INT);$action=$_POST['action']??'';
 if(!$id){flash('error','Produk tidak valid.');redirect(page_url('seller-products'));}
 if($action==='archive'){$repo->archive((int)$id,$sellerId);flash('success','Produk diarsipkan.');}
 elseif($action==='restore'){$repo->restore((int)$id,$sellerId);flash('success','Produk diaktifkan kembali.');}
 elseif($action==='stock'){$qty=filter_input(INPUT_POST,'quantity',FILTER_VALIDATE_INT,['options'=>['min_range'=>0]]);if($qty===false||$qty===null){flash('error','Stok harus 0 atau lebih.');}else{$repo->setStock((int)$id,$sellerId,(int)$qty);flash('success','Stok diperbarui.');}}
 else{flash('error','Aksi tidak valid.');}
 redirect(page_url('seller-products'));
}
$products=$repo->bySeller($sellerId);$pageTitle='Produk Seller';require __DIR__.'/../includes/header.php';
?><section class="section-padding page-section"><div class="container"><div class="page-toolbar d-flex justify-content-between align-items-center"><?=back_link('seller-dashboard','Kembali ke dashboard')?><a class="btn btn-primary btn-sm" href="<?=e(page_url('seller-product-form'))?>"><i class="bi bi-plus-lg me-1"></i>Tambah produk</a></div><div class="section-heading mb-4"><span class="eyebrow">Seller</span><h2>Produk <em>kamu.</em></h2><p class="text-muted">Tambah, edit, arsipkan, dan atur stok katalog kamu.</p></div>
<?php if(!$products):?><div class="glass-card empty-state"><span><i class="bi bi-box-seam"></i></span><h2>Belum ada produk</h2><p>Tambahkan produk pertama agar muncul di marketplace.</p><a class="btn btn-primary" href="<?=e(page_url('seller-product-form'))?>">Tambah produk</a></div><?php else:?><div class="row g-4"><?php foreach($products as $p):?><div class="col-md-6 col-lg-4"><div class="glass-card p-4 h-100"><div class="d-flex justify-content-between align-items-start"><span class="badge text-bg-light"><?=e($p['status'])?></span><small class="text-muted"><?=e($p['category'])?></small></div><?php if($p['image_path']):?><img class="product-thumb mt-3" src="<?=e(APP_URL.'/'.$p['image_path'])?>" alt="<?=e($p['name'])?>"><?php else:?><div class="product-thumb product-thumb-empty mt-3"><i class="bi bi-box-seam"></i></div><?php endif;?><h3 class="h5 mt-3 mb-1"><?=e($p['name'])?></h3><strong><?=format_price((int)$p['price'])?></strong><p class="text-muted mt-1 mb-3">Stok: <?=intval($p['stock'])?></p><div class="d-flex gap-2 flex-wrap"><a class="btn btn-soft btn-sm" href="<?=e(page_url('seller-product-form',['id'=>$p['id']]))?>"><i class="bi bi-pencil me-1"></i>Edit</a><?php if($p['status']==='archived'):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="restore"><input type="hidden" name="product_id" value="<?=intval($p['id'])?>"><button class="btn btn-soft btn-sm">Aktifkan</button></form><?php else:?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="archive"><input type="hidden" name="product_id" value="<?=intval($p['id'])?>"><button class="btn btn-outline-danger btn-sm">Hapus / Arsipkan</button></form><?php endif;?></div><form class="d-flex gap-2 mt-3" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="stock"><input type="hidden" name="product_id" value="<?=intval($p['id'])?>"><input class="form-control form-control-sm" type="number" min="0" name="quantity" value="<?=intval($p['stock'])?>"><button class="btn btn-primary btn-sm">Simpan stok</button></form></div></div><?php endforeach;?></div><?php endif;?></div></section><?php require __DIR__.'/../includes/footer.php'; ?>