<?php
declare(strict_types=1);
class CartRepository{
 public function getOrCreateId(int $userId):int{$st=db()->prepare('SELECT id FROM carts WHERE user_id=? LIMIT 1');$st->execute([$userId]);$id=$st->fetchColumn();if($id)return(int)$id;try{$st=db()->prepare('INSERT INTO carts(user_id) VALUES(?)');$st->execute([$userId]);return(int)db()->lastInsertId();}catch(Throwable){$st=db()->prepare('SELECT id FROM carts WHERE user_id=? LIMIT 1');$st->execute([$userId]);return(int)$st->fetchColumn();}}
 public function items(int $userId):array{$st=db()->prepare("SELECT ci.id cart_item_id,ci.product_id,ci.quantity,p.name,p.price,p.status,p.seller_id,p.city,COALESCE(NULLIF(u.shop_name,''),u.full_name) seller_name,COALESCE(i.quantity,0) stock,(SELECT pi.image_path FROM product_images pi WHERE pi.product_id=p.id ORDER BY pi.sort_order,pi.id LIMIT 1) image_path FROM carts c JOIN cart_items ci ON ci.cart_id=c.id JOIN products p ON p.id=ci.product_id JOIN users u ON u.id=p.seller_id LEFT JOIN product_inventory i ON i.product_id=p.id WHERE c.user_id=? ORDER BY ci.id DESC");$st->execute([$userId]);return$st->fetchAll();}
 public function add(int $userId,int $productId,int $quantity):void{$p=db()->prepare("SELECT p.status,COALESCE(i.quantity,0) stock FROM products p LEFT JOIN product_inventory i ON i.product_id=p.id WHERE p.id=? LIMIT 1");$p->execute([$productId]);$row=$p->fetch();if(!$row||$row['status']!=='available'||(int)$row['stock']<1)throw new RuntimeException('Produk tidak tersedia.');if($quantity<1)throw new RuntimeException('Jumlah tidak valid.');$cartId=$this->getOrCreateId($userId);$existing=$this->findByProduct($cartId,$productId);$newQty=($existing?(int)$existing['quantity']:0)+$quantity;if($newQty>(int)$row['stock'])throw new RuntimeException('Jumlah melebihi stok tersedia.');$st=db()->prepare('INSERT INTO cart_items(cart_id,product_id,quantity) VALUES(?,?,?) ON DUPLICATE KEY UPDATE quantity=quantity+VALUES(quantity),updated_at=CURRENT_TIMESTAMP');$st->execute([$cartId,$productId,$quantity]);}
 private function findByProduct(int $cartId,int $productId):?array{$st=db()->prepare('SELECT id,quantity FROM cart_items WHERE cart_id=? AND product_id=? LIMIT 1');$st->execute([$cartId,$productId]);return$st->fetch()?:null;}
 public function update(int $userId,int $cartItemId,int $quantity):void{if($quantity<1)throw new RuntimeException('Jumlah harus minimal 1.');$item=$this->findItemForUser($cartItemId,$userId);if(!$item)throw new RuntimeException('Item keranjang tidak ditemukan.');if($item['status']!=='available')throw new RuntimeException('Produk sudah tidak tersedia.');if($quantity>(int)$item['stock'])throw new RuntimeException('Jumlah melebihi stok tersedia.');$st=db()->prepare('UPDATE cart_items ci JOIN carts c ON c.id=ci.cart_id SET ci.quantity=? WHERE ci.id=? AND c.user_id=?');$st->execute([$quantity,$cartItemId,$userId]);}
 public function findItemForUser(int $cartItemId,int $userId):?array{$st=db()->prepare("SELECT ci.*,p.price,p.status,COALESCE(i.quantity,0) stock FROM cart_items ci JOIN carts c ON c.id=ci.cart_id JOIN products p ON p.id=ci.product_id LEFT JOIN product_inventory i ON i.product_id=p.id WHERE ci.id=? AND c.user_id=? LIMIT 1");$st->execute([$cartItemId,$userId]);return$st->fetch()?:null;}
 public function remove(int $userId,int $cartItemId):void{db()->prepare('DELETE ci FROM cart_items ci JOIN carts c ON c.id=ci.cart_id WHERE ci.id=? AND c.user_id=?')->execute([$cartItemId,$userId]);}
}
